version: '3'

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER:      demo
      POSTGRES_PASSWORD:  demo
      POSTGRES_DB:        demo
    ports:
      - "5432:5432"
    volumes:
      - ./.compose/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./migrations/:/docker-entrypoint-initdb.d/